CELL_SIZE = 20
SCREEN_WIDTH = 950
SCREEN_HEIGHT = 600
GRID_ROWS = SCREEN_HEIGHT // CELL_SIZE
GRID_COLUMNS = SCREEN_WIDTH // CELL_SIZE
ROW_MARGIN = (SCREEN_WIDTH - (CELL_SIZE * GRID_COLUMNS)) / 2
COLUMN_MARGIN = (SCREEN_HEIGHT - (CELL_SIZE * GRID_ROWS)) / 2

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLUMNS = GRID_COLUMNS

# Shift maze left and center vertically
MAZE_LEVEL_START_X = -440.0
MAZE_LEVEL_START_Y = 250.0

PLAYER_MOVE_SPEED = 4

TURN_TOLERANCE = 5
BUFFER_FRAMES = 12
