CELL_SIZE = 30
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 850
GRID_ROWS = SCREEN_HEIGHT // CELL_SIZE
GRID_COLUMNS = SCREEN_WIDTH // CELL_SIZE
ROW_MARGIN = (SCREEN_WIDTH - (CELL_SIZE * GRID_COLUMNS)) / 2
COLUMN_MARGIN = (SCREEN_HEIGHT - (CELL_SIZE * GRID_ROWS)) / 2

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLUMNS = GRID_COLUMNS

MAZE_LEVEL_START_X = (-SCREEN_WIDTH / 2) + ROW_MARGIN + CELL_SIZE / 2
MAZE_LEVEL_START_Y = (SCREEN_HEIGHT / 2) - COLUMN_MARGIN - (CELL_SIZE * 5 / 2)

PLAYER_MOVE_SPEED = 5

TURN_TOLERANCE = 8
BUFFER_FRAMES = 12
