CELL_SIZE = 30
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 850
GRID_ROWS = SCREEN_HEIGHT // CELL_SIZE
GRID_COLS = SCREEN_WIDTH // CELL_SIZE
ROW_MARGIN = (SCREEN_WIDTH - (GRID_ROWS * CELL_SIZE)) / 2
COL_MARGIN = (SCREEN_HEIGHT - (GRID_COLS * CELL_SIZE)) / 2

MAZE_GRID_ROWS = GRID_ROWS - 2
MAZE_GRID_COLS = GRID_COLS

MAZE_LEVEL_START_X = (-SCREEN_WIDTH / 2) + ROW_MARGIN + CELL_SIZE / 2
MAZE_LEVEL_START_Y = (SCREEN_HEIGHT / 2) - COL_MARGIN - (CELL_SIZE * 5 / 2)